name: guide_it
description: "Create guides and showcase the features of your app in an easy ad customizable way"
version: 0.0.3
repository: https://github.com/tratteo/guide_it

environment:
    sdk: ">=3.2.3 <4.0.0"
    flutter: ">=1.17.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.1
    auto_exporter: ^1.5.0
    dependency_validator: ^3.2.3
    build_runner: ^2.4.7

flutter:
